Replaced the 8_bit_register exercise for an improved pipo_register one, added all necessary documentation and updated both the test script and the yaml file to include this new exercise as well.

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -26,34 +26,32 @@ jobs:
           cd practice_exercises
           for d in */; do
             folder_name=${d%/}
-            if [ $folder_name != "register_8_bit" ]; then
-              echo "🧪 Testing $folder_name exercise"
-                nvc -a "$d"/*.vhd || {
-                  echo "❌ Analysis failed in $folder_name exercise"
-                  rm -rf work
-                  exit 1
-                }
-                shopt -s nullglob
+            echo "🧪 Testing $folder_name exercise"
+              nvc -a "$d"/*.vhd || {
+                echo "❌ Analysis failed in $folder_name exercise"
+                rm -rf work
+                exit 1
+              }
+              shopt -s nullglob
 
-                tbfiles=( "$d"/*_tb.vhd )
-                if (( ${#tbfiles[@]} == 0 )); then
-                  echo "❌ No testbench found in $folder_name exercise"
-                  rm -rf work
-                  exit 1
-                fi
+              tbfiles=( "$d"/*_tb.vhd )
+              if (( ${#tbfiles[@]} == 0 )); then
+                echo "❌ No testbench found in $folder_name exercise"
+                rm -rf work
+                exit 1
+              fi
 
-                tbname=$(basename "${tbfiles[0]}" .vhd)
-                nvc -e "$tbname" || {
-                  echo "❌ Elaboration failed for $tbname in $folder_name exercise"
-                  rm -rf work
-                  exit 1
-                }
-                nvc -r "$tbname" --exit-severity=error || {
-                  echo "❌ Simulation failed for $tbname in $folder_name exercise"
-                  rm -rf work
-                  exit 1
-                }
-              echo "✅ $folder_name test passed"
-            fi
+              tbname=$(basename "${tbfiles[0]}" .vhd)
+              nvc -e "$tbname" || {
+                echo "❌ Elaboration failed for $tbname in $folder_name exercise"
+                rm -rf work
+                exit 1
+              }
+              nvc -r "$tbname" --exit-severity=error || {
+                echo "❌ Simulation failed for $tbname in $folder_name exercise"
+                rm -rf work
+                exit 1
+              }
+            echo "✅ $folder_name test passed"
           done
           echo "✅ All tests passed!"
